(define (problem log-f)
  (:domain logistics-strips)
  (:objects package1 package2 package3 package4 package5 package6 package7
            package8 package9 package10 package11 package12 package13
            package14 airplane1 airplane2 airplane3 pgh bos la ny sf chi atl
            den pgh-truck bos-truck la-truck ny-truck sf-truck chi-truck
            atl-truck den-truck pgh-po pgh-central pgh-airport bos-po
            bos-central bos-airport la-po la-central la-airport ny-po
            ny-central ny-airport sf-po sf-central sf-airport chi-po
            chi-central chi-airport atl-po atl-central atl-airport den-po
            den-central den-airport)
  (:init (obj package1)
	 (obj package2)
	 (obj package3)
	 (obj package4)
	 (obj package5)
	 (obj package6)
	 (obj package7)
	 (obj package8)
	 (obj package9)
	 (obj package10)
	 (obj package11)
	 (obj package12)
	 (obj package13)
	 (obj package14)
	 (airplane airplane1)
	 (airplane airplane2)
	 (airplane airplane3)
	 (city pgh)
	 (city bos)
	 (city la)
	 (city ny)
	 (city sf)
	 (city chi)
	 (city atl)
	 (city den)
	 (truck pgh-truck)
	 (truck bos-truck)
	 (truck la-truck)
	 (truck ny-truck)
	 (truck sf-truck)
	 (truck chi-truck)
	 (truck atl-truck)
	 (truck den-truck)
	 (location pgh-po)
	 (location pgh-central)
	 (location pgh-airport)
	 (airport pgh-airport)
	 (location bos-po)
	 (location bos-central)
	 (location bos-airport)
	 (airport bos-airport)
	 (location la-po)
	 (location la-central)
	 (location la-airport)
	 (airport la-airport)
	 (location ny-po)
	 (location ny-central)
	 (location ny-airport)
	 (airport ny-airport)
	 (location sf-po)
	 (location sf-central)
	 (location sf-airport)
	 (airport sf-airport)
	 (location chi-po)
	 (location chi-central)
	 (location chi-airport)
	 (airport chi-airport)
	 (location atl-po)
	 (location atl-central)
	 (location atl-airport)
	 (airport atl-airport)
	 (location den-po)
	 (location den-central)
	 (location den-airport)
	 (airport den-airport)
	 (in-city pgh-po pgh)
	 (in-city pgh-central pgh)
	 (in-city pgh-airport pgh)
	 (in-city bos-po bos)
	 (in-city bos-central bos)
	 (in-city bos-airport bos)
	 (in-city la-po la)
	 (in-city la-central la)
	 (in-city la-airport la)
	 (in-city ny-po ny)
	 (in-city ny-central ny)
	 (in-city ny-airport ny)
	 (in-city sf-po sf)
	 (in-city sf-central sf)
	 (in-city sf-airport sf)
	 (in-city chi-po chi)
	 (in-city chi-central chi)
	 (in-city chi-airport chi)
	 (in-city atl-po atl)
	 (in-city atl-central atl)
	 (in-city atl-airport atl)
	 (in-city den-po den)
	 (in-city den-central den)
	 (in-city den-airport den)
	 (at package1 bos-central)
	 (at package2 pgh-po)
	 (at package3 sf-airport)
	 (at package4 den-central)
	 (at package5 den-airport)
	 (at package6 ny-airport)
	 (at package7 la-central)
	 (at package8 pgh-central)
	 (at package9 atl-central)
	 (at package10 chi-airport)
	 (at package11 den-central)
	 (at package12 atl-po)
	 (at package13 atl-po)
	 (at package14 ny-po)
	 (at airplane1 pgh-airport)
	 (at airplane2 pgh-airport)
	 (at airplane3 pgh-airport)
	 (at pgh-truck pgh-po)
	 (at bos-truck bos-po)
	 (at la-truck la-po)
	 (at ny-truck ny-airport)
	 (at sf-truck sf-airport)
	 (at chi-truck chi-airport)
	 (at atl-truck atl-airport)
	 (at den-truck den-po))
  (:goal (and (at package1 ny-central)
	      (at package2 den-central)
	      (at package3 bos-airport)
	      (at package4 bos-po)
	      (at package5 atl-airport)
	      (at package6 pgh-airport)
	      (at package7 ny-airport)
	      (at package8 sf-central)
	      (at package9 bos-airport)
	      (at package10 sf-central)
	      (at package11 pgh-central)
	      (at package12 pgh-po)
	      (at package13 la-airport)
	      (at package14 chi-central))))
