(define (problem log-e)
  (:domain logistics-strips)
  (:objects package1 package2 package3 package4 package5 package6 package7
            package8 package9 package10 package11 airplane1 airplane2 pgh
            bos la ny sf chi pgh-truck bos-truck la-truck ny-truck sf-truck
            chi-truck pgh-po pgh-central pgh-airport bos-po bos-central
            bos-airport la-po la-central la-airport ny-po ny-central
            ny-airport sf-po sf-central sf-airport chi-po chi-central
            chi-airport)
  (:init (obj package1)
	 (obj package2)
	 (obj package3)
	 (obj package4)
	 (obj package5)
	 (obj package6)
	 (obj package7)
	 (obj package8)
	 (obj package9)
	 (obj package10)
	 (obj package11)
	 (airplane airplane1)
	 (airplane airplane2)
	 (city pgh)
	 (city bos)
	 (city la)
	 (city ny)
	 (city sf)
	 (city chi)
	 (truck pgh-truck)
	 (truck bos-truck)
	 (truck la-truck)
	 (truck ny-truck)
	 (truck sf-truck)
	 (truck chi-truck)
	 (location pgh-po)
	 (location pgh-central)
	 (location pgh-airport)
	 (airport pgh-airport)
	 (location bos-po)
	 (location bos-central)
	 (location bos-airport)
	 (airport bos-airport)
	 (location la-po)
	 (location la-central)
	 (location la-airport)
	 (airport la-airport)
	 (location ny-po)
	 (location ny-central)
	 (location ny-airport)
	 (airport ny-airport)
	 (location sf-po)
	 (location sf-central)
	 (location sf-airport)
	 (airport sf-airport)
	 (location chi-po)
	 (location chi-central)
	 (location chi-airport)
	 (airport chi-airport)
	 (in-city pgh-po pgh)
	 (in-city pgh-central pgh)
	 (in-city pgh-airport pgh)
	 (in-city bos-po bos)
	 (in-city bos-central bos)
	 (in-city bos-airport bos)
	 (in-city la-po la)
	 (in-city la-central la)
	 (in-city la-airport la)
	 (in-city ny-po ny)
	 (in-city ny-central ny)
	 (in-city ny-airport ny)
	 (in-city sf-po sf)
	 (in-city sf-central sf)
	 (in-city sf-airport sf)
	 (in-city chi-po chi)
	 (in-city chi-central chi)
	 (in-city chi-airport chi)
	 (at package1 sf-airport)
	 (at package2 chi-airport)
	 (at package3 sf-airport)
	 (at package4 chi-central)
	 (at package5 la-po)
	 (at package6 chi-central)
	 (at package7 bos-airport)
	 (at package8 sf-airport)
	 (at package9 bos-central)
	 (at package10 chi-airport)
	 (at package11 pgh-central)
	 (at airplane1 pgh-airport)
	 (at airplane2 pgh-airport)
	 (at pgh-truck pgh-central)
	 (at bos-truck bos-central)
	 (at la-truck la-airport)
	 (at ny-truck ny-airport)
	 (at sf-truck sf-airport)
	 (at chi-truck chi-airport))
  (:goal (and (at package1 chi-central)
	      (at package2 sf-central)
	      (at package3 la-central)
	      (at package4 sf-central)
	      (at package5 pgh-airport)
	      (at package6 la-central)
	      (at package7 pgh-central)
	      (at package8 bos-central)
	      (at package9 pgh-central)
	      (at package10 sf-po)
	      (at package11 sf-po))))
